export const ROOT_GROUPS = [
  {
    id: 'foundation',
    label: 'Foundation',
    range: [1, 4],
    description: 'These Roots establish the learner, income, present cash flow, and preparedness.',
  },
  {
    id: 'structure-expansion',
    label: 'Structure and Expansion',
    range: [5, 8],
    description: 'These Roots examine borrowing, protection, earning expansion, and consumer leverage.',
  },
  {
    id: 'ownership-legacy',
    label: 'Ownership and Legacy',
    range: [9, 11],
    description: 'These Roots move toward ownership, generational wealth, and the doorway to entrepreneurship.',
  },
];

export const ROOT_CATALOG = [
  {
    id: 1,
    slug: 'one',
    label: 'Root One',
    title: 'The Story Beneath the Decision',
    purpose: 'Understand the person making the financial decisions.',
    description: 'Recognize the experiences, beliefs, emotions, inherited messages, habits, assumptions, and pressures operating beneath financial decisions.',
    capacity: 'Recognize what is influencing a financial choice while a choice is still available.',
    status: 'published',
    accent: '#d8b66a',
  },
  {
    id: 2,
    slug: 'two',
    label: 'Root Two',
    title: 'Value & Earning',
    purpose: 'Understand how work and value become income.',
    description: 'Explore how labor, skill, time, knowledge, service, responsibility, negotiation, access, opportunity, and market value become income.',
    capacity: 'Distinguish work performed, value created, compensation received, and the systems that influence earning capacity.',
    status: 'published',
    accent: '#77b9d0',
  },
  {
    id: 3,
    slug: 'three',
    label: 'Root Three',
    title: 'Choice, Cash Flow & Spending',
    purpose: 'Understand how income moves through present life.',
    description: 'Learn cash flow, banking, spending, timing, obligations, priorities, expenses, payment systems, account balances, and everyday financial choices.',
    capacity: 'See how timing, obligations, priorities, and choices direct the movement of present income.',
    status: 'published',
    accent: '#eb9b58',
  },
  {
    id: 4,
    slug: 'four',
    label: 'Root Four',
    title: 'Saving, Preparedness & Resilience',
    purpose: 'Understand how present money is carried forward for preparedness.',
    description: 'Build saving, reserves, emergency preparation, sinking funds, future expenses, margin, short-term goals, and future options.',
    capacity: 'Carry present resources forward in ways that protect access, flexibility, and recovery.',
    status: 'published',
    accent: '#8ebf9b',
  },
  {
    id: 5,
    slug: 'five',
    label: 'Root Five',
    title: 'Credit, Debt & Future Income',
    purpose: 'Understand how borrowing claims future income.',
    description: 'Examine credit, debt, borrowing costs, repayment terms, credit records, affordability, debt difficulty, and the complete future claim created by borrowing.',
    capacity: 'Keep access, cost, obligation, timing, and consequence visible in the same borrowing decision.',
    status: 'published',
    accent: '#e2ae5b',
  },
  {
    id: 6,
    slug: 'six',
    label: 'Root Six',
    title: 'Financial Protection & Risk',
    purpose: 'Understand how to protect what has been built.',
    description: 'Explore insurance, identity protection, fraud, account security, contracts, legal authority, financial abuse, trusted professionals, beneficiary protection, and preparation for disruption.',
    capacity: 'Identify, reduce, transfer, and prepare for risks that could interrupt financial progress.',
    status: 'published',
    accent: '#77a9a7',
  },
  {
    id: 7,
    slug: 'seven',
    label: 'Root Seven',
    title: 'Earning Expansion & Income Diversity',
    purpose: 'Understand how to increase and diversify income.',
    description: 'Explore skill development, negotiation, additional income streams, career movement, side income, scalable value, concentration risk, and earning-capacity tradeoffs.',
    capacity: 'Evaluate how additional earning capacity can widen choice without hiding cost, risk, or responsibility.',
    status: 'published',
    accent: '#9cae66',
  },
  {
    id: 8,
    slug: 'eight',
    label: 'Root Eight',
    title: 'Ownership, Investing & the Future',
    purpose: 'Understand how ownership and investing can widen future choice.',
    description: 'Explore ownership claims, investing, time, risk, return, diversification, fees, taxes, access, speculation, provider trust, and the responsibility attached to future money.',
    capacity: 'Evaluate future ownership choices independently with purpose, risk, cost, access, capacity, and responsibility in view.',
    status: 'published',
    accent: '#a7d625',
  },
  {
    id: 9,
    slug: 'nine',
    label: 'Root Nine',
    title: 'Ownership, Investing & Financial Freedom',
    purpose: 'Understand ownership, investing, and financial freedom.',
    description: 'Explore assets, risk, return, diversification, time, compounding, market participation, property, alternative ownership, income-producing assets, and financial independence.',
    capacity: 'Evaluate the movement from consumption toward ownership with risk, time, return, and purpose in view.',
    status: 'published',
    accent: '#ad8ac3',
  },
  {
    id: 10,
    slug: 'ten',
    label: 'Root Ten',
    title: 'Family, Legacy & Generational Wealth',
    purpose: 'Understand family, legacy, and generational wealth.',
    description: 'Explore shared responsibility, household decisions, dependents, caregiving, estate concepts, beneficiaries, inheritance, family communication, generational patterns, and asset transfer.',
    capacity: 'Make shared and long-range financial choices with roles, relationships, authority, care, and transfer responsibilities visible.',
    status: 'published',
    accent: '#d18183',
  },
  {
    id: 11,
    slug: 'eleven',
    label: 'Root Eleven',
    title: 'The Doorway to Entrepreneurship',
    purpose: 'Open the doorway to entrepreneurship.',
    description: 'Explore value creation, problem solving, products and services, employment and ownership, independent work, business systems, risk, responsibility, scalability, non-owner wealth creation, and alternative investing.',
    capacity: 'Recognize entrepreneurship as one possible form of value creation while preserving corporate, professional, licensed, scientific, and non-owner paths to wealth.',
    status: 'published',
    accent: '#d4a04f',
    note: 'Root Eleven is the doorway into the separate Business Hub. It is not the full Business Hub curriculum.',
  },
];
