import { useMemo, useState } from 'react';
import {
  ArrowLeft, ArrowRight, BookOpen, Calculator, CalendarDays, Check, CircleDollarSign,
  Gauge, Headphones, Search, ShieldCheck, SlidersHorizontal, WalletCards,
} from 'lucide-react';
import { moneyDictionary } from './money-dictionary-data';
import {
  estimatedPayoffDate, futureClaim, money, monthlyReserve,
  simulateBalance, sum, TOOL_DISCLAIMER, utilization,
} from './tools-calculations';
import { getTool, toolCategories, toolRegistry, toolRoute } from './tools-registry';
import { queueSageVoice } from './sage-voice-events';
import { ApprovedArtwork } from './approved-artwork';
import './tools-center.css';
import './tools-center-fixes.css';

const INTRO = 'Financial information becomes useful when you can apply it to a real decision. These tools help you make costs, timing, obligations, and tradeoffs visible. They provide estimates and comparisons—not instructions about which choice you should make.';

function ToolsHeader({ title = 'Tools Center' }) {
  const from = new URLSearchParams(window.location.search).get('from'); const returnPath = from?.startsWith('/roots/') ? from : '';
  return <header className="tools-header"><a href="/grove" className="tools-brand"><ApprovedArtwork variant="tree" /><span><strong>Root$Wise</strong><small>{title}</small></span></a><nav aria-label="Tools navigation">{returnPath && <a href={returnPath}>Return to Lesson</a>}<a href="/grove">Grove</a><a href="/tools">All tools</a><a href="/tools/dictionary">Dictionary</a></nav></header>;
}

function ListenButton({ text, label = 'Listen with Sage' }) {
  return <button type="button" className="tools-listen" onClick={() => queueSageVoice(text, 'Sage is ready to guide this tool.')}><Headphones /> {label}</button>;
}

function ToolFrame({ tool, children, assumptions }) {
  const sourceGroup = ['debt-cost', 'offer-compare', 'minimum-payment', 'debt-spiral'].includes(tool.kind) ? 'borrowing' : tool.kind === 'utilization' ? 'credit' : null;
  return <main className="tools-page tool-detail-page"><ToolsHeader title={tool.title} /><section className="tool-detail-hero"><div><a className="tools-back" href="/tools"><ArrowLeft /> All tools</a><p>{toolCategories.find((item) => item.id === tool.category)?.label}</p><h1>{tool.title}</h1><span>{tool.summary}</span><ListenButton text={`${tool.title}. ${tool.summary} Enter a scenario to make the relationship visible. Results are estimates, not a direction about which choice to make.`} /></div></section><section className="tool-workspace"><div className="tool-session-note"><ShieldCheck /><p><strong>Private by default.</strong> Entries stay in this browser tab and are not saved, transmitted to Sage, or added to your RootWise profile. Do not enter account numbers, Social Security numbers, or other sensitive identifiers.</p></div>{children}{assumptions && <details className="tool-assumptions"><summary>Calculation assumptions and limits</summary><div>{assumptions}</div></details>}<p className="tool-disclaimer">{TOOL_DISCLAIMER}</p>{sourceGroup === 'borrowing' && <p className="tool-source-note">Reference: <a href="https://www.consumerfinance.gov/ask-cfpb/what-is-the-difference-between-a-loan-interest-rate-and-the-apr-en-733/" target="_blank" rel="noreferrer">CFPB · Interest rate and APR</a>. This calculator is a simplified monthly estimate; an actual agreement can use different timing or calculation methods.</p>}{sourceGroup === 'credit' && <p className="tool-source-note">Reference: <a href="https://www.consumerfinance.gov/ask-cfpb/will-paying-off-my-credit-card-balance-every-month-improve-my-score-en-1293/" target="_blank" rel="noreferrer">CFPB · Reported balances and credit scores</a>. Scoring models and reporting dates vary.</p>}</section></main>;
}

function Field({ label, value, onChange, min = 0, max = undefined, step = '0.01', prefix = '', suffix = '', type = 'number' }) {
  return <label className="tool-field"><span>{label}</span><div>{prefix && <i>{prefix}</i>}<input type={type} min={min} max={max} step={step} value={value} onChange={(event) => onChange(event.target.value)} />{suffix && <i>{suffix}</i>}</div></label>;
}

function SelectField({ label, value, onChange, children }) {
  return <label className="tool-field"><span>{label}</span><select value={value} onChange={(event) => onChange(event.target.value)}>{children}</select></label>;
}

function TextField({ label, value, onChange, type = 'text', placeholder = '' }) {
  return <label className="tool-field"><span>{label}</span><input type={type} value={value} placeholder={placeholder} onChange={(event) => onChange(event.target.value)} /></label>;
}

function Results({ title = 'What becomes visible', items, children = null }) {
  return <section className="tool-results" aria-live="polite"><p>{title}</p><div>{items.map((item) => <span className={item.negative ? 'is-negative' : ''} key={item.label}><small>{item.label}</small><strong>{item.value}</strong></span>)}</div>{children}</section>;
}

function DebtCostTool() {
  const [values, setValues] = useState({ principal: 4200, rate: 24, payment: 140, extra: 35, fees: 0 });
  const set = (key) => (value) => setValues({ ...values, [key]: value });
  const balance = Number(values.principal) + Number(values.fees);
  const base = simulateBalance({ balance, annualRate: values.rate, payment: values.payment });
  const withExtra = simulateBalance({ balance, annualRate: values.rate, payment: Number(values.payment) + Number(values.extra) });
  const timeDifference = base.payoff && withExtra.payoff ? Math.max(0, base.months - withExtra.months) : null;
  const interestDifference = base.payoff && withExtra.payoff ? Math.max(0, base.interestPaid - withExtra.interestPaid) : null;
  return <CalculatorLayout fields={<><Field label="Amount borrowed or current balance" prefix="$" value={values.principal} onChange={set('principal')} /><Field label="Fixed annual interest rate" suffix="%" max={1000} value={values.rate} onChange={set('rate')} /><Field label="Required monthly payment" prefix="$" value={values.payment} onChange={set('payment')} /><Field label="Optional additional payment" prefix="$" value={values.extra} onChange={set('extra')} /><Field label="Optional fees added to the modeled balance" prefix="$" value={values.fees} onChange={set('fees')} /></>} results={<Results items={[{ label: 'Estimated repayment time', value: base.payoff ? `${base.months} ${base.months === 1 ? 'month' : 'months'}` : 'Balance may not decline' }, { label: 'Estimated total interest', value: money(base.interestPaid) }, { label: 'Estimated total repayment', value: base.payoff ? money(base.paid) : 'No payoff shown' }, { label: 'Estimated payoff date', value: base.payoff ? estimatedPayoffDate(base.months) : 'Not available' }, { label: 'Time difference with entered extra', value: timeDifference === null ? 'Not available' : `${timeDifference} ${timeDifference === 1 ? 'month' : 'months'}` }, { label: 'Interest difference with entered extra', value: interestDifference === null ? 'Not available' : money(interestDifference) }]}>{!base.payoff && <p className="result-warning">{base.reason} Under these assumptions, the balance may not decline.</p>}<p className="result-note">The additional-payment comparison uses only the amount you entered. RootWise does not recommend an additional-payment amount.</p></Results>} />;
}

function OfferCompareTool() {
  const [offers, setOffers] = useState(/** @type {Record<string,string|number>} */ ({ aPrice: 18000, aDown: 2000, aFinanced: 16000, aRate: 8, aApr: 8.6, aFees: 300, aPayment: 391, aMonths: 48, aType: 'Fixed', bPrice: 18000, bDown: 2000, bFinanced: 16000, bRate: 10, bApr: 10.8, bFees: 650, bPayment: 297, bMonths: 72, bType: 'Variable' }));
  const set = (key) => (value) => setOffers({ ...offers, [key]: value });
  const resultFor = (prefix) => { const paymentTotal = Number(offers[`${prefix}Payment`]) * Number(offers[`${prefix}Months`]); const financed = Number(offers[`${prefix}Financed`]); const fees = Number(offers[`${prefix}Fees`]); return { payment: Number(offers[`${prefix}Payment`]), interest: Math.max(0, paymentTotal - financed), fees, repayment: Number(offers[`${prefix}Down`]) + paymentTotal + fees, months: Number(offers[`${prefix}Months`]), type: offers[`${prefix}Type`] }; };
  const a = resultFor('a'); const b = resultFor('b');
  const fields = (prefix, label) => <section className="tool-input-panel"><h2>{label}</h2><div className="tool-field-grid"><Field label="Cash price" prefix="$" value={offers[`${prefix}Price`]} onChange={set(`${prefix}Price`)} /><Field label="Down payment" prefix="$" value={offers[`${prefix}Down`]} onChange={set(`${prefix}Down`)} /><Field label="Amount financed" prefix="$" value={offers[`${prefix}Financed`]} onChange={set(`${prefix}Financed`)} /><Field label="Interest rate" suffix="%" value={offers[`${prefix}Rate`]} onChange={set(`${prefix}Rate`)} /><Field label="APR when available" suffix="%" value={offers[`${prefix}Apr`]} onChange={set(`${prefix}Apr`)} /><Field label="Fees" prefix="$" value={offers[`${prefix}Fees`]} onChange={set(`${prefix}Fees`)} /><Field label="Monthly payment" prefix="$" value={offers[`${prefix}Payment`]} onChange={set(`${prefix}Payment`)} /><Field label="Number of payments" step="1" value={offers[`${prefix}Months`]} onChange={set(`${prefix}Months`)} /><SelectField label="Rate structure" value={offers[`${prefix}Type`]} onChange={set(`${prefix}Type`)}><option>Fixed</option><option>Variable</option></SelectField></div></section>;
  const comparison = [`${a.payment < b.payment ? 'Offer A' : 'Offer B'} has the lower monthly payment`, `${a.repayment < b.repayment ? 'Offer A' : 'Offer B'} has the lower estimated total repayment`, `${a.months < b.months ? 'Offer A' : 'Offer B'} has the shorter obligation`, `${a.fees > b.fees ? 'Offer A' : 'Offer B'} has higher fees`];
  return <><div className="comparison-inputs">{fields('a', 'Offer A')}{fields('b', 'Offer B')}</div><div className="offer-results"><Results title="Offer A" items={[{ label: 'Monthly payment', value: money(a.payment) }, { label: 'Estimated total interest', value: money(a.interest) }, { label: 'Total fees', value: money(a.fees) }, { label: 'Estimated total repayment', value: money(a.repayment) }, { label: 'Obligation length', value: `${a.months} months` }]} /><Results title="Offer B" items={[{ label: 'Monthly payment', value: money(b.payment) }, { label: 'Estimated total interest', value: money(b.interest) }, { label: 'Total fees', value: money(b.fees) }, { label: 'Estimated total repayment', value: money(b.repayment) }, { label: 'Obligation length', value: `${b.months} months` }]} /></div><Results title="Difference between the entered offers" items={[{ label: 'Payment difference', value: money(Math.abs(a.payment - b.payment)) }, { label: 'Interest difference', value: money(Math.abs(a.interest - b.interest)) }, { label: 'Fee difference', value: money(Math.abs(a.fees - b.fees)) }, { label: 'Repayment difference', value: money(Math.abs(a.repayment - b.repayment)) }, { label: 'Term difference', value: `${Math.abs(a.months - b.months)} months` }]}><ul className="comparison-language">{comparison.map((item) => <li key={item}>{item}</li>)}</ul></Results><p className="tool-interpretation">No offer is labeled “best.” APR and interest rate are displayed as entered; the repayment estimate uses the entered payment count. A variable rate can change, so this static view cannot predict later payments or total cost.</p></>;
}

function BalanceSimulator({ minimum = false, spiral = false }) {
  const [values, setValues] = useState({ balance: 4200, rate: 24, payment: 140, charge: spiral ? 90 : 0, rule: 'Percentage plus floor', fixedMinimum: 95, percent: 2, floor: 35, extra: 0 });
  const set = (key) => (value) => setValues({ ...values, [key]: value });
  const fixedMinimumMode = minimum && values.rule === 'Fixed minimum';
  const result = simulateBalance({ balance: values.balance, annualRate: values.rate, payment: fixedMinimumMode ? Number(values.fixedMinimum) + Number(values.extra) : values.payment, monthlyCharge: values.charge, mode: minimum && !fixedMinimumMode ? 'minimum' : 'fixed', percent: values.percent, floor: values.floor, extra: values.extra });
  const maxPoint = Math.max(...result.points.map((point) => point.balance), Number(values.balance), 1);
  return <CalculatorLayout fields={<><Field label="Starting balance" prefix="$" value={values.balance} onChange={set('balance')} /><Field label="Fixed annual rate" suffix="%" value={values.rate} onChange={set('rate')} />{minimum ? <><SelectField label="Minimum-payment rule" value={values.rule} onChange={set('rule')}><option>Percentage plus floor</option><option>Fixed minimum</option></SelectField>{fixedMinimumMode ? <Field label="Fixed minimum payment" prefix="$" value={values.fixedMinimum} onChange={set('fixedMinimum')} /> : <><Field label="Minimum percentage" suffix="%" value={values.percent} onChange={set('percent')} /><Field label="Minimum floor" prefix="$" value={values.floor} onChange={set('floor')} /></>}<Field label="Optional additional payment" prefix="$" value={values.extra} onChange={set('extra')} /></> : <Field label="Monthly payment" prefix="$" value={values.payment} onChange={set('payment')} />}<Field label="Optional new monthly charges" prefix="$" value={values.charge} onChange={set('charge')} /></>} results={<Results items={[{ label: 'Estimated payoff time', value: result.payoff ? `${result.months} months` : 'No payoff shown' }, { label: 'Estimated total interest', value: money(result.interestPaid) }, { label: 'Estimated amount paid', value: money(result.paid) }, { label: 'Balance at stopping point', value: money(result.finalBalance), negative: !result.payoff }, { label: 'Continuing new charges', value: money(values.charge) }]}>{!result.payoff && <p className="result-warning">{result.reason}</p>}<div className="balance-chart" aria-label="Estimated balance over time">{result.points.slice(-12).map((point) => <span key={point.month}><i style={{ height: `${Math.max(3, point.balance / maxPoint * 100)}%` }} /><small>{point.month === 0 ? 'Start' : `M${point.month}`}</small></span>)}</div></Results>} />;
}

function FutureIncomeTool() {
  const [items, setItems] = useState(/** @type {Array<Record<string,string|number>>} */ ([{ name: 'Auto loan', type: 'Installment', balance: 9400, payment: 410, due: '2026-08-12', rateType: 'Fixed', end: '2028-07-12', promo: '', secured: 'Vehicle', shared: 'None', status: 'Current' }, { name: 'Credit card', type: 'Revolving', balance: 2600, payment: 95, due: '2026-08-18', rateType: 'Variable', end: '2029-02-18', promo: '', secured: 'None', shared: 'None', status: 'Current' }, { name: 'Furniture plan', type: 'Installment', balance: 720, payment: 80, due: '2026-08-25', rateType: 'Fixed', end: '2027-04-25', promo: '2026-12-25', secured: 'None', shared: 'Joint borrower', status: 'Current' }]));
  const update = (index, key, value) => setItems(items.map((item, i) => i === index ? { ...item, [key]: value } : item));
  const monthlyClaims = sum(items.map((item) => item.payment)); const balances = sum(items.map((item) => item.balance));
  const timeline = [...items].filter((item) => item.end).sort((a, b) => String(a.end).localeCompare(String(b.end)));
  return <><div className="tool-input-panel"><h2>Approximate or fictional obligations</h2><div className="obligation-list">{items.map((item, index) => <fieldset key={index}><legend>Obligation {index + 1}</legend><TextField label="Obligation name" value={item.name} onChange={(value) => update(index, 'name', value)} /><SelectField label="Debt type" value={item.type} onChange={(value) => update(index, 'type', value)}><option>Installment</option><option>Revolving</option><option>Informal</option><option>Other</option></SelectField><Field label="Balance" prefix="$" value={item.balance} onChange={(value) => update(index, 'balance', value)} /><Field label="Required payment" prefix="$" value={item.payment} onChange={(value) => update(index, 'payment', value)} /><TextField label="Due date" type="date" value={item.due} onChange={(value) => update(index, 'due', value)} /><SelectField label="Interest-rate type" value={item.rateType} onChange={(value) => update(index, 'rateType', value)}><option>Fixed</option><option>Variable</option><option>Unknown</option><option>None</option></SelectField><TextField label="Expected ending date" type="date" value={item.end} onChange={(value) => update(index, 'end', value)} /><TextField label="Promotional expiration" type="date" value={item.promo} onChange={(value) => update(index, 'promo', value)} /><TextField label="Secured property" value={item.secured} onChange={(value) => update(index, 'secured', value)} /><TextField label="Joint borrower or cosigner" value={item.shared} onChange={(value) => update(index, 'shared', value)} /><SelectField label="Account status" value={item.status} onChange={(value) => update(index, 'status', value)}><option>Current</option><option>Past due</option><option>In review</option><option>Paid</option></SelectField></fieldset>)}</div></div><Results items={[{ label: 'Total required monthly debt payments', value: money(monthlyClaims) }, { label: 'Future income committed each month', value: money(monthlyClaims) }, { label: 'Balances represented', value: money(balances) }, { label: 'Obligations mapped', value: String(items.length) }]}><ol className="cash-timeline">{timeline.map((item) => <li key={`${item.name}-${item.end}`}><span>{item.end} · {item.name}</span><strong>{money(item.payment)} monthly flexibility may return</strong></li>)}</ol><p className="result-note">Ending dates are learner-entered expectations, not payoff predictions. No account numbers or identifiers are needed.</p></Results></>;
}

function BnplTool() {
  const [plans, setPlans] = useState(/** @type {Array<{name:string,amount:string|number,remaining:string|number,next:string,interval:string|number}>} */ ([{ name: 'Shoes', amount: 45, remaining: 3, next: '2026-08-05', interval: 14 }, { name: 'Tablet', amount: 80, remaining: 4, next: '2026-08-12', interval: 14 }, { name: 'Repair', amount: 95, remaining: 2, next: '2026-08-19', interval: 14 }]));
  const update = (index, key, value) => setPlans(plans.map((plan, i) => i === index ? { ...plan, [key]: value } : plan));
  const schedule = plans.flatMap((plan) => Array.from({ length: Math.min(26, Math.max(0, Number(plan.remaining))) }, (_, index) => { const date = new Date(`${plan.next}T12:00:00`); date.setDate(date.getDate() + index * Number(plan.interval)); const weekStart = new Date(date); weekStart.setDate(date.getDate() - date.getDay()); return { name: plan.name, amount: Number(plan.amount), date, dateKey: Number.isNaN(date.getTime()) ? 'Date needed' : date.toISOString().slice(0, 10), week: Number.isNaN(date.getTime()) ? 'Date needed' : `Week of ${weekStart.toISOString().slice(0, 10)}`, month: Number.isNaN(date.getTime()) ? 'Date needed' : date.toLocaleDateString('en-US', { month: 'long', year: 'numeric' }) }; })).sort((a, b) => a.date.getTime() - b.date.getTime());
  const monthTotals = schedule.reduce((groups, item) => ({ ...groups, [item.month]: (groups[item.month] || 0) + item.amount }), {});
  const weekTotals = schedule.reduce((groups, item) => ({ ...groups, [item.week]: (groups[item.week] || 0) + item.amount }), {});
  const dateCounts = schedule.reduce((groups, item) => ({ ...groups, [item.dateKey]: (groups[item.dateKey] || 0) + 1 }), {});
  return <><div className="tool-input-panel"><h2>Several installment purchases on one calendar</h2><div className="bnpl-plan-list">{plans.map((plan, index) => <fieldset key={index}><legend>Installment purchase {index + 1}</legend><TextField label="Purchase name" value={plan.name} onChange={(value) => update(index, 'name', value)} /><Field label="Individual payment" prefix="$" value={plan.amount} onChange={(value) => update(index, 'amount', value)} /><Field label="Payments remaining" step="1" value={plan.remaining} onChange={(value) => update(index, 'remaining', value)} /><TextField label="Next payment date" type="date" value={plan.next} onChange={(value) => update(index, 'next', value)} /><Field label="Days between payments" step="1" value={plan.interval} onChange={(value) => update(index, 'interval', value)} /></fieldset>)}</div></div><Results items={[{ label: 'Total amount still committed', value: money(schedule.reduce((total, item) => total + item.amount, 0)) }, { label: 'Payments mapped', value: String(schedule.length) }, { label: 'Dates with overlapping obligations', value: String(Object.values(dateCounts).filter((count) => count > 1).length) }, { label: 'Weeks represented', value: String(Object.keys(weekTotals).length) }, { label: 'Months represented', value: String(Object.keys(monthTotals).length) }]}><div className="bnpl-calendar">{schedule.slice(0, 12).map((item, index) => <span key={`${item.name}-${item.dateKey}-${index}`}><small>{item.dateKey}</small><strong>{item.name}{dateCounts[item.dateKey] > 1 ? ' · overlaps' : ''}</strong><i>{money(item.amount)}</i></span>)}</div><p className="result-note">Combined by week: {Object.entries(weekTotals).slice(0, 6).map(([week, total]) => `${week} ${money(total)}`).join(' · ') || 'Add valid dates to begin.'}</p><p className="result-note">Combined by month: {Object.entries(monthTotals).map(([month, total]) => `${month} ${money(total)}`).join(' · ') || 'Add valid dates to begin.'}</p></Results></>;
}

function DebtSpiralTool() {
  const [v, setV] = useState({ income: 3200, baseline: 3100, timing: 'Income arrives after key obligations', shortage: 300, rate: 36, payment: 90, newExpenses: 125, additional: 75 }); const set = (key) => (value) => setV({ ...v, [key]: value });
  const timingGap = v.timing.includes('after') ? Number(v.payment) : 0;
  const scenario = Array.from({ length: 6 }).reduce((state, _, index) => { const interest = state.balance * Number(v.rate) / 1200; const flexibility = Number(v.income) - Number(v.baseline) - Number(v.payment) - Number(v.newExpenses); const nextShortage = Math.max(0, -flexibility) + timingGap; const newBorrowing = Number(v.additional) + nextShortage; const balance = Math.max(0, state.balance + interest + newBorrowing - Number(v.payment)); return { balance, cost: state.cost + interest, repeating: state.repeating + (newBorrowing > 0 ? 1 : 0), months: [...state.months, { month: index + 1, balance, flexibility, newBorrowing }] }; }, /** @type {{balance:number,cost:number,repeating:number,months:Array<{month:number,balance:number,flexibility:number,newBorrowing:number}>}} */ ({ balance: Number(v.shortage), cost: 0, repeating: 0, months: [] }));
  const { balance, cost, repeating, months } = scenario;
  const stages = [['1', 'Cash-flow shortage', money(v.shortage)], ['2', 'Borrowing fills the immediate gap', money(v.shortage)], ['3', 'New required payment', money(v.payment)], ['4', 'Reduced future flexibility', money(months[0]?.flexibility)], ['5', 'Another shortage', money(Math.max(0, -months[0]?.flexibility) + timingGap)], ['6', 'Additional borrowing', money(months[0]?.newBorrowing)], ['7', 'Estimated fees and interest accumulate', money(cost)], ['8', 'Dependence repeats in the model', `${repeating} of 6 months`]];
  return <><CalculatorLayout fields={<><Field label="Monthly take-home income" prefix="$" value={v.income} onChange={set('income')} /><Field label="Baseline monthly expenses" prefix="$" value={v.baseline} onChange={set('baseline')} /><SelectField label="Income timing" value={v.timing} onChange={set('timing')}><option>Income arrives before key obligations</option><option>Income arrives after key obligations</option></SelectField><Field label="Initial shortage" prefix="$" value={v.shortage} onChange={set('shortage')} /><Field label="Borrowing cost (annual rate estimate)" suffix="%" value={v.rate} onChange={set('rate')} /><Field label="New required payment" prefix="$" value={v.payment} onChange={set('payment')} /><Field label="New expenses each month" prefix="$" value={v.newExpenses} onChange={set('newExpenses')} /><Field label="Additional borrowing each month" prefix="$" value={v.additional} onChange={set('additional')} /></>} results={<Results items={[{ label: 'Modeled ending balance after 6 months', value: money(balance), negative: balance > Number(v.shortage) }, { label: 'Estimated interest added', value: money(cost) }, { label: 'Months requiring more borrowing', value: `${repeating} of 6` }, { label: 'Monthly flexibility before new borrowing', value: money(months[0]?.flexibility), negative: months[0]?.flexibility < 0 }]}><p className="result-note">This is a changeable scenario, not a prediction of the learner’s future.</p></Results>} /><section className="spiral-stages" aria-label="Debt spiral stages">{stages.map(([number, title, value]) => <article key={number}><span>{number}</span><div><strong>{title}</strong><small>{value}</small></div></article>)}</section></>;
}

function CashFlowTool() {
  const [v, setV] = useState(/** @type {Record<string,string|number>} */ ({ opening: 300, income1: 2200, incomeDay1: 1, income2: 2200, incomeDay2: 15, bill1: 1800, billDay1: 3, bill2: 1700, billDay2: 12, bill3: 600, billDay3: 24 }));
  const set = (key) => (value) => setV({ ...v, [key]: value });
  const events = [{ type: 'Opening', day: 0, amount: Number(v.opening) }, { type: 'Income', day: Number(v.incomeDay1), amount: Number(v.income1) }, { type: 'Bill', day: Number(v.billDay1), amount: -Number(v.bill1) }, { type: 'Bill', day: Number(v.billDay2), amount: -Number(v.bill2) }, { type: 'Income', day: Number(v.incomeDay2), amount: Number(v.income2) }, { type: 'Bill', day: Number(v.billDay3), amount: -Number(v.bill3) }].sort((a, b) => a.day - b.day);
  const cash = events.reduce((state, event) => { const running = state.running + event.amount; return { running, lowest: Math.min(state.lowest, running), timeline: [...state.timeline, { ...event, running }] }; }, { running: 0, lowest: Infinity, timeline: [] });
  const { running, lowest, timeline } = cash;
  return <CalculatorLayout fields={<>{Object.entries({ opening: 'Opening cash', income1: 'Income 1', incomeDay1: 'Income 1 day', income2: 'Income 2', incomeDay2: 'Income 2 day', bill1: 'Bill group 1', billDay1: 'Bill group 1 day', bill2: 'Bill group 2', billDay2: 'Bill group 2 day', bill3: 'Bill group 3', billDay3: 'Bill group 3 day' }).map(([key, label]) => <Field key={key} label={label} prefix={key.toLowerCase().includes('day') ? '' : '$'} min={key.toLowerCase().includes('day') ? 1 : 0} max={key.toLowerCase().includes('day') ? 31 : undefined} step={key.toLowerCase().includes('day') ? '1' : '0.01'} value={v[key]} onChange={set(key)} />)}</>} results={<Results items={[{ label: 'Month-end estimate', value: money(running), negative: running < 0 }, { label: 'Lowest point in month', value: money(lowest), negative: lowest < 0 }]}><ol className="cash-timeline">{timeline.map((event, index) => <li key={`${event.type}-${event.day}-${index}`}><span>Day {event.day || 'start'} · {event.type}</span><strong className={event.running < 0 ? 'is-negative' : ''}>{money(event.running)}</strong></li>)}</ol></Results>} />;
}

function IrregularTool() {
  const [v, setV] = useState({ name: 'Vehicle registration', amount: 420, frequency: 'Annual', occurrences: 1 }); const set = (key) => (value) => setV({ ...v, [key]: value }); const monthly = Number(v.amount) * Number(v.occurrences) / 12;
  return <CalculatorLayout fields={<><TextField label="Expense name or purpose" value={v.name} onChange={set('name')} /><Field label="Amount each time" prefix="$" value={v.amount} onChange={set('amount')} /><SelectField label="Expense pattern" value={v.frequency} onChange={set('frequency')}><option>Annual</option><option>Quarterly</option><option>Seasonal</option><option>Unpredictable but likely</option></SelectField><Field label="Estimated times per year" step="1" value={v.occurrences} onChange={set('occurrences')} /></>} results={<Results items={[{ label: 'Monthly planning amount', value: money(monthly) }, { label: 'Annual amount represented', value: money(monthly * 12) }, { label: 'Pattern selected', value: v.frequency }]}><p className="result-note">For unpredictable-but-likely costs, use an approximate amount and frequency. The plan can be revised when better information appears.</p></Results>} />;
}

function ReserveTool() {
  const [v, setV] = useState({ purpose: 'Repair reserve', target: 3000, saved: 450, targetDate: '2027-07-01', contribution: 175, schedule: 'Monthly' }); const set = (key) => (value) => setV({ ...v, [key]: value }); const target = new Date(`${v.targetDate}T12:00:00`); const now = new Date(); const months = Number.isNaN(target.getTime()) ? 1 : Math.max(1, Math.ceil((target.getFullYear() - now.getFullYear()) * 12 + target.getMonth() - now.getMonth())); const result = monthlyReserve(v.target, v.saved, months); const monthlyContribution = v.schedule === 'Weekly' ? Number(v.contribution) * 52 / 12 : Number(v.contribution); const projected = Number(v.saved) + monthlyContribution * months;
  return <CalculatorLayout fields={<><TextField label="Purpose" value={v.purpose} onChange={set('purpose')} /><Field label="Target amount" prefix="$" value={v.target} onChange={set('target')} /><TextField label="Target date" type="date" value={v.targetDate} onChange={set('targetDate')} /><Field label="Existing amount" prefix="$" value={v.saved} onChange={set('saved')} /><Field label="Possible contribution" prefix="$" value={v.contribution} onChange={set('contribution')} /><SelectField label="Contribution schedule" value={v.schedule} onChange={set('schedule')}><option>Monthly</option><option>Weekly</option></SelectField></>} results={<Results items={[{ label: 'Remaining target', value: money(result.remaining) }, { label: 'Monthly amount matching target and date', value: money(result.monthly) }, { label: 'Projected amount with entered schedule', value: money(projected) }, { label: 'Approximate months available', value: String(months) }]}><p className="result-note">The target belongs to the learner. This planner does not recommend a universal emergency-fund amount.</p></Results>} />;
}

function UtilizationTool() {
  const [v, setV] = useState(/** @type {Record<string,string|number>} */ ({ balance1: 900, limit1: 3000, balance2: 350, limit2: 2000, balance3: 0, limit3: 1000, changeType: 'Payment', changeAmount: 300, changeAccount: '1' })); const set = (key) => (value) => setV({ ...v, [key]: value }); const accounts = [1, 2, 3].map((index) => ({ index, balance: Number(v[`balance${index}`]), limit: Number(v[`limit${index}`]), current: utilization(v[`balance${index}`], v[`limit${index}`]) })); const changed = accounts.map((account) => { if (String(account.index) !== String(v.changeAccount)) return account; const amount = Number(v.changeAmount); const balance = Math.max(0, account.balance + (v.changeType === 'Purchase' ? amount : v.changeType === 'Payment' || v.changeType === 'Refund' ? -amount : 0)); const limit = Math.max(0, account.limit + (v.changeType === 'Limit increase' ? amount : v.changeType === 'Limit decrease' ? -amount : 0)); return { ...account, balance, limit }; }); const currentTotal = utilization(sum(accounts.map((account) => account.balance)), sum(accounts.map((account) => account.limit))); const changedTotal = utilization(sum(changed.map((account) => account.balance)), sum(changed.map((account) => account.limit)));
  return <CalculatorLayout fields={<>{accounts.map((account) => <fieldset className="inline-account" key={account.index}><legend>Revolving account {account.index}</legend><Field label="Current or reported balance" prefix="$" value={v[`balance${account.index}`]} onChange={set(`balance${account.index}`)} /><Field label="Credit limit" prefix="$" value={v[`limit${account.index}`]} onChange={set(`limit${account.index}`)} /></fieldset>)}<SelectField label="Modeled change" value={v.changeType} onChange={set('changeType')}><option>Payment</option><option>Purchase</option><option>Refund</option><option>Limit increase</option><option>Limit decrease</option></SelectField><SelectField label="Account receiving change" value={v.changeAccount} onChange={set('changeAccount')}><option value="1">Account 1</option><option value="2">Account 2</option><option value="3">Account 3</option></SelectField><Field label="Change amount" prefix="$" value={v.changeAmount} onChange={set('changeAmount')} /></>} results={<Results items={[{ label: 'Current combined utilization', value: currentTotal.ratio === null ? 'Enter a limit' : `${currentTotal.ratio.toFixed(1)}%` }, { label: 'Combined utilization after change', value: changedTotal.ratio === null ? 'Enter a limit' : `${changedTotal.ratio.toFixed(1)}%` }, { label: 'Available credit after change', value: money(changedTotal.available) }, ...accounts.map((account) => ({ label: `Account ${account.index} current utilization`, value: account.current.ratio === null ? 'No limit entered' : `${account.current.ratio.toFixed(1)}%` }))]}><p className="result-note">This explores arithmetic, not a score outcome. Reporting dates, balances used by a scoring model, and model versions vary. RootWise does not promise score increases.</p></Results>} />;
}

const checklistItems = ['Personal information', 'Open accounts', 'Closed accounts', 'Balances', 'Credit limits', 'Payment history', 'Collections', 'Hard inquiries', 'Authorized-user accounts', 'Duplicate information', 'Unfamiliar information', 'Items requiring documentation or investigation'];
function ChecklistTool() {
  const [checked, setChecked] = useState({}); const count = Object.values(checked).filter(Boolean).length;
  return <><section className="tool-checklist"><h2>Review without entering account details</h2>{checklistItems.map((item) => <label key={item}><input type="checkbox" checked={Boolean(checked[item])} onChange={() => setChecked({ ...checked, [item]: !checked[item] })} /><span><Check />{item}</span></label>)}</section><Results items={[{ label: 'Review steps checked', value: `${count} of ${checklistItems.length}` }]}><p className="result-note">A checked item means reviewed—not necessarily correct. Use the reporting company’s current instructions and applicable rights for any dispute.</p></Results></>;
}

function AffordabilityTool() {
  const [v, setV] = useState(/** @type {Record<string,string|number>} */ ({ income: 4200, proposed: 650, essential: 2200, debts: 450, irregular: 180, insurance: 300, caregiving: 250, reserve: 250, incomeChange: 0 })); const set = (key) => (value) => setV({ ...v, [key]: value }); const remaining = Number(v.income) - Number(v.incomeChange) - sum([v.proposed, v.essential, v.debts, v.irregular, v.insurance, v.caregiving, v.reserve]); const outside = sum([v.irregular, v.insurance, v.caregiving, v.reserve]);
  return <CalculatorLayout fields={<>{Object.entries({ income: 'Take-home income', proposed: 'Proposed payment', essential: 'Essential expenses', debts: 'Current debt payments', irregular: 'Irregular expenses (monthly equivalent)', insurance: 'Insurance', caregiving: 'Dependents or caregiving expenses', reserve: 'Emergency reserve contribution', incomeChange: 'Optional income reduction scenario' }).map(([key, label]) => <Field key={key} label={label} prefix="$" value={v[key]} onChange={set(key)} />)}</>} results={<Results items={[{ label: 'Under the information entered, this payment would leave approximately', value: money(remaining), negative: remaining < 0 }, { label: 'Expenses modeled beyond the proposed payment', value: money(outside) }, { label: 'Effect of entered income interruption', value: money(v.incomeChange) }, { label: 'Proposed payment tested', value: money(v.proposed) }]}><p className="result-note">Some household expenses may be absent from a lender’s underwriting model. This tool does not approve, deny, or declare a purchase affordable; it makes the entered tradeoffs visible.</p></Results>} />;
}

function TransportationTool() {
  const labels = ['Vehicle payment', 'Insurance', 'Fuel or charging', 'Registration monthly equivalent', 'Maintenance', 'Repairs', 'Parking', 'Tolls', 'Estimated depreciation']; const [values, setValues] = useState(/** @type {number[]} */ ([410, 165, 150, 24, 55, 65, 40, 20, 185])); const monthly = sum(values);
  return <CalculatorLayout fields={<>{labels.map((label, index) => <Field key={label} label={label} prefix="$" value={values[index]} onChange={(value) => setValues(values.map((item, i) => i === index ? Number(value) : item))} />)}</>} results={<Results items={[{ label: 'Visible monthly transportation cost', value: money(monthly) }, { label: 'Visible annual transportation cost', value: money(monthly * 12) }, { label: 'Payment alone', value: money(values[0]) }, { label: 'Other modeled monthly costs', value: money(monthly - values[0]) }]}><p className="result-note">Depreciation is an economic estimate rather than a bill. Actual ownership and use costs vary.</p></Results>} />;
}

function HousingTool() {
  const labels = ['Rent or principal and interest', 'Taxes', 'Insurance', 'Association fees', 'Utilities', 'Maintenance', 'Repairs', 'Upfront costs monthly equivalent']; const [a, setA] = useState(/** @type {number[]} */ ([1650, 0, 25, 0, 220, 0, 0, 100])); const [b, setB] = useState(/** @type {number[]} */ ([1850, 260, 120, 85, 260, 175, 90, 350])); const [mobilityA, setMobilityA] = useState('More mobility'); const [mobilityB, setMobilityB] = useState('Less mobility'); const [termA, setTermA] = useState(12); const [termB, setTermB] = useState(360); const totalA = sum(a); const totalB = sum(b);
  const panel = (name, values, setter, mobility, setMobility, term, setTerm) => <section className="tool-input-panel"><h2>{name}</h2>{labels.map((label, index) => <Field key={label} label={label} prefix="$" value={values[index]} onChange={(value) => setter(values.map((item, i) => i === index ? Number(value) : item))} />)}<SelectField label="Mobility" value={mobility} onChange={setMobility}><option>More mobility</option><option>Moderate mobility</option><option>Less mobility</option></SelectField><Field label="Length of obligation (months)" step="1" value={term} onChange={(value) => setTerm(Number(value))} /></section>;
  return <><div className="comparison-inputs">{panel('Housing structure A', a, setA, mobilityA, setMobilityA, termA, setTermA)}{panel('Housing structure B', b, setB, mobilityB, setMobilityB, termB, setTermB)}</div><Results items={[{ label: 'Structure A visible monthly cost', value: money(totalA) }, { label: 'Structure B visible monthly cost', value: money(totalB) }, { label: 'Monthly difference', value: money(Math.abs(totalA - totalB)) }, { label: 'Obligation-length difference', value: `${Math.abs(termA - termB)} months` }]}><p className="result-note">Structure A: {mobilityA}. Structure B: {mobilityB}. This comparison does not declare renting or owning universally superior.</p></Results></>;
}

function EducationTool() {
  const [v, setV] = useState(/** @type {Record<string,string|number>} */ ({ tuition: 18000, fees: 1200, supplies: 900, living: 12000, grants: 5000, scholarships: 2500, borrowed: 18000, completion: 24, credential: 'Associate degree', repayment: 260, repaymentMonths: 120, completionQuestion: 'What completion supports are available?', requirementQuestion: 'Is this credential required for the roles being considered?', pathwayQuestion: 'What entry-level income range is supported by current job data?' })); const set = (key) => (value) => setV({ ...v, [key]: value }); const gross = sum([v.tuition, v.fees, v.supplies, v.living]); const aid = sum([v.grants, v.scholarships]); const net = Math.max(0, gross - aid); const estimatedRepayment = Number(v.repayment) * Number(v.repaymentMonths);
  return <CalculatorLayout fields={<><Field label="Tuition" prefix="$" value={v.tuition} onChange={set('tuition')} /><Field label="Fees" prefix="$" value={v.fees} onChange={set('fees')} /><Field label="Supplies" prefix="$" value={v.supplies} onChange={set('supplies')} /><Field label="Living expenses" prefix="$" value={v.living} onChange={set('living')} /><Field label="Grants" prefix="$" value={v.grants} onChange={set('grants')} /><Field label="Scholarships" prefix="$" value={v.scholarships} onChange={set('scholarships')} /><Field label="Amount borrowed" prefix="$" value={v.borrowed} onChange={set('borrowed')} /><Field label="Completion time (months)" step="1" value={v.completion} onChange={set('completion')} /><TextField label="Credential" value={v.credential} onChange={set('credential')} /><Field label="Estimated monthly repayment" prefix="$" value={v.repayment} onChange={set('repayment')} /><Field label="Estimated repayment months" step="1" value={v.repaymentMonths} onChange={set('repaymentMonths')} /><TextField label="Completion question" value={v.completionQuestion} onChange={set('completionQuestion')} /><TextField label="Credential-requirement question" value={v.requirementQuestion} onChange={set('requirementQuestion')} /><TextField label="Realistic income-pathway question" value={v.pathwayQuestion} onChange={set('pathwayQuestion')} /></>} results={<Results items={[{ label: 'Gross education and living cost', value: money(gross) }, { label: 'Grants and scholarships entered', value: money(aid) }, { label: 'Net cost before other resources', value: money(net) }, { label: 'Amount borrowed entered', value: money(v.borrowed) }, { label: 'Estimated scheduled repayment', value: money(estimatedRepayment) }, { label: 'Completion time', value: `${v.completion} months` }]}><p className="result-note">Credential: {v.credential || 'Not entered'}. The questions keep completion, requirements, and realistic income pathways in the frame. RootWise does not guarantee career or income outcomes.</p></Results>} />;
}

function FutureClaimTool() {
  const [v, setV] = useState({ benefitName: 'Transportation access', benefit: 1500, benefitDuration: 'The benefit may last several years', payment: 72, months: 24, fees: 50, choices: 'Reduces monthly room for another goal until the obligation ends' }); const set = (key) => (value) => setV({ ...v, [key]: value }); const result = futureClaim(v);
  return <CalculatorLayout fields={<><TextField label="What becomes available now" value={v.benefitName} onChange={set('benefitName')} /><Field label="Present benefit or cash price" prefix="$" value={v.benefit} onChange={set('benefit')} /><TextField label="How long the benefit may last" value={v.benefitDuration} onChange={set('benefitDuration')} /><Field label="Payment required" prefix="$" value={v.payment} onChange={set('payment')} /><Field label="Length of obligation (months)" step="1" value={v.months} onChange={set('months')} /><Field label="Additional fees" prefix="$" value={v.fees} onChange={set('fees')} /><TextField label="Future choices affected" value={v.choices} onChange={set('choices')} /></>} results={<Results items={[{ label: 'What becomes available now', value: v.benefitName }, { label: 'Present benefit', value: money(result.benefit) }, { label: 'Total estimated future claim', value: money(result.totalClaim) }, { label: 'Claim above present benefit', value: money(result.difference), negative: result.difference > 0 }, { label: 'Length of obligation', value: `${v.months} months` }]}><p className="result-note">Benefit duration: {v.benefitDuration || 'Not entered'}. Future choice affected: {v.choices || 'Not entered'}.</p></Results>} />;
}

function DecisionMapTool() {
  const [answers, setAnswers] = useState(/** @type {Record<string,string>} */ ({ decision: '', purpose: '', facts: '', missing: '', obligations: '', options: '', emotional: '', social: '', inherited: '', immediate: '', future: '', possible: '', removes: '', learnerDecision: '', reasoning: '', reviewDate: '' }));
  const prompts = { decision: 'Decision', purpose: 'Purpose', facts: 'Financial facts', missing: 'Missing information', obligations: 'Current obligations', options: 'Available options', emotional: 'Emotional influences', social: 'Social influences', inherited: 'Inherited rules', immediate: 'Immediate consequences', future: 'Future consequences', possible: 'What each option makes possible', removes: 'What each option removes', learnerDecision: 'Learner’s decision', reasoning: 'Learner’s reasoning', reviewDate: 'Date for later review' };
  const completed = Object.values(answers).filter((value) => value.trim()).length;
  return <><section className="decision-map">{Object.entries(prompts).map(([key, prompt], index) => <label key={key}><span>{String(index + 1).padStart(2, '0')}</span><strong>{prompt}</strong>{key === 'reviewDate' ? <input type="date" value={answers[key]} onChange={(event) => setAnswers({ ...answers, [key]: event.target.value })} /> : <textarea value={answers[key]} onChange={(event) => setAnswers({ ...answers, [key]: event.target.value })} placeholder="Write only what is useful for this decision. Do not enter sensitive identifiers." />}</label>)}</section><Results items={[{ label: 'Map sections completed', value: `${completed} of 16` }]}><p className="result-note">This map does not select an option. It helps the learner develop and record decision capacity. Entries disappear when the tab is closed or refreshed.</p></Results></>;
}

function CalculatorLayout({ fields, results }) { return <div className="calculator-layout"><section className="tool-input-panel"><h2>Enter a learning scenario</h2><div className="tool-field-grid">{fields}</div></section>{results}</div>; }

function ToolCalculator({ kind }) {
  if (kind === 'debt-cost') return <DebtCostTool />;
  if (kind === 'offer-compare') return <OfferCompareTool />;
  if (kind === 'minimum-payment') return <BalanceSimulator minimum />;
  if (kind === 'debt-spiral') return <DebtSpiralTool />;
  if (kind === 'future-income') return <FutureIncomeTool />;
  if (kind === 'bnpl') return <BnplTool />;
  if (kind === 'cash-flow') return <CashFlowTool />;
  if (kind === 'irregular') return <IrregularTool />;
  if (kind === 'reserve') return <ReserveTool />;
  if (kind === 'utilization') return <UtilizationTool />;
  if (kind === 'checklist') return <ChecklistTool />;
  if (kind === 'affordability') return <AffordabilityTool />;
  if (kind === 'transportation') return <TransportationTool />;
  if (kind === 'housing') return <HousingTool />;
  if (kind === 'education') return <EducationTool />;
  if (kind === 'future-claim') return <FutureClaimTool />;
  if (kind === 'decision-map') return <DecisionMapTool />;
  return null;
}

export function ToolsCenter() {
  const featured = toolRegistry.filter((tool) => tool.featured);
  const additionalBorrowing = toolRegistry.filter((tool) => tool.category === 'borrowing' && !tool.featured);
  const categories = [{ ...toolCategories.find((category) => category.id === 'borrowing'), id: 'borrowing-more', tools: additionalBorrowing }, ...toolCategories.filter((category) => category.id !== 'borrowing').map((category) => ({ ...category, tools: toolRegistry.filter((tool) => tool.category === category.id) }))];
  return <main className="tools-page"><ToolsHeader /><section className="tools-hero"><div><p>Make the decision visible</p><h1>RootWise Tools</h1><blockquote>{INTRO}</blockquote><ListenButton text={INTRO} label="Hear Sage introduce the Tools Center" /></div><div className="tools-hero-orbit" aria-hidden="true"><Calculator /><CalendarDays /><Gauge /></div></section><section className="tools-content"><div className="tools-privacy"><ShieldCheck /><div><strong>Session-only by default</strong><span>Your entries are not saved to a profile or sent to Sage. Avoid sensitive identifiers.</span></div></div><section className="featured-tools" aria-labelledby="featured-title"><header><p>Start with the complete picture</p><h2 id="featured-title">Borrowing tools that reveal more than the payment</h2></header><div>{featured.map((tool) => <a href={toolRoute(tool)} key={tool.slug}><CircleDollarSign /><span><small>{toolCategories.find((item) => item.id === tool.category)?.label}</small><strong>{tool.title}</strong><p>{tool.summary}</p></span><ArrowRight /></a>)}</div></section>{categories.map((category) => <section className={`tool-category tool-category-${category.id}`} aria-labelledby={`category-${category.id}`} key={category.id}><header><p>{category.id === 'borrowing-more' ? 'More borrowing views' : category.label}</p><h2 id={`category-${category.id}`}>{category.description}</h2></header><div>{category.tools.map((tool) => <a href={toolRoute(tool)} key={tool.slug}><span>{tool.kind === 'dictionary' ? <BookOpen /> : tool.category === 'credit' ? <WalletCards /> : <SlidersHorizontal />}</span><strong>{tool.title}</strong><p>{tool.summary}</p><i>Open tool <ArrowRight /></i></a>)}</div></section>)}<p className="tool-disclaimer center">{TOOL_DISCLAIMER}</p></section></main>;
}

export function ToolDetail({ slug }) {
  const tool = getTool(slug);
  if (!tool || tool.kind === 'dictionary') return <ToolsCenter />;
  const assumptions = tool.kind === 'minimum-payment' ? <><p>Interest is estimated once per month using the entered fixed annual rate divided by 12. New charges are added before that month’s estimated interest and payment. A percentage minimum is the greater of the entered percentage or floor, plus any extra payment, capped at the amount owed.</p><p>Actual card agreements may use a daily balance method, different minimum formulas, fees, changing rates, and different payment allocation. The display stops at 1,200 months. Continued charges can prevent payoff. Currency is displayed to the nearest cent while calculations keep additional precision.</p></> : tool.kind === 'debt-cost' ? <><p>Optional fees are added to the modeled balance. Interest is estimated monthly using the entered fixed annual rate divided by 12, with one payment per month and the first modeled payment one month from now. The display stops at 1,200 months.</p><p>The additional-payment result compares the required payment with the required payment plus only the entered extra amount. Actual timing, compounding, fees, allocation, and payoff quotes can differ. Currency is displayed to the nearest cent while calculations keep additional precision.</p></> : tool.kind === 'offer-compare' ? <><p>Totals use the entered monthly payment multiplied by the entered number of payments, plus the entered down payment and fees. Interest is estimated as scheduled payments above the entered amount financed; inconsistent inputs can create an incomplete comparison.</p><p>APR is displayed as entered and is not recalculated. Variable rates can change. Currency is displayed to the nearest cent.</p></> : tool.kind === 'debt-spiral' ? <><p>The six-month scenario applies the entered annual borrowing-cost estimate monthly, then adds modeled timing gaps, new expenses, and additional borrowing before subtracting the required payment.</p><p>It is a structural illustration, not a forecast. Actual agreements, fees, payment timing, income, and events differ.</p></> : null;
  return <ToolFrame tool={tool} assumptions={assumptions}><ToolCalculator kind={tool.kind} /></ToolFrame>;
}

function DictionaryCard({ entry }) {
  return <article id={entry.slug}><span>{entry.term[0]}</span><div><p>{entry.topic}{entry.rootId ? ` · Root ${entry.rootId}` : ''}</p><h2>{entry.term}</h2><blockquote>{entry.definition}</blockquote><div className="dictionary-detail"><strong>Why it matters</strong><p>{entry.whyItMatters}</p><strong>Simple example</strong><p>{entry.example}</p>{entry.relatedTerms.length > 0 && <><strong>Related terms</strong><p>{entry.relatedTerms.join(' · ')}</p></>}</div>{entry.lesson && <a href={entry.lesson}>Continue in {entry.lessonLabel} <ArrowRight /></a>}</div></article>;
}

export function MoneyDictionary() {
  const [query, setQuery] = useState(''); const [topic, setTopic] = useState('All');
  const topics = ['All', ...new Set(moneyDictionary.map((entry) => entry.topic))];
  const entries = useMemo(() => moneyDictionary.filter((entry) => (topic === 'All' || entry.topic === topic) && `${entry.term} ${entry.definition}`.toLowerCase().includes(query.toLowerCase())), [query, topic]);
  const params = new URLSearchParams(window.location.search); const returnPath = params.get('from'); const safeReturn = returnPath?.startsWith('/roots/') ? returnPath : '';
  return <main className="tools-page dictionary-page"><ToolsHeader title="Money Dictionary" /><section className="dictionary-hero"><div><a className="tools-back" href="/tools"><ArrowLeft /> Tools Center</a><p>Plain language, connected learning</p><h1>Money Dictionary</h1><span>Words become useful when you can recognize what they do inside a real decision.</span><ListenButton text="Welcome to the Money Dictionary. Search for a term, read its plain-language meaning, and follow a connected lesson when one is published. A definition gives you a starting point; the agreement and the facts of a real situation still matter." /></div></section><section className="dictionary-content">{safeReturn && <a className="return-to-lesson" href={safeReturn}><ArrowLeft /> Return to lesson</a>}<div className="dictionary-controls"><label><Search /><span>Search terms and definitions</span><input type="search" value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Try APR, cash flow, or credit report" /></label><label><SlidersHorizontal /><span>Filter by topic</span><select value={topic} onChange={(event) => setTopic(event.target.value)}>{topics.map((item) => <option key={item}>{item}</option>)}</select></label></div><p className="dictionary-count">{entries.length} {entries.length === 1 ? 'definition' : 'definitions'}</p><div className="dictionary-list">{entries.map((entry) => <DictionaryCard entry={entry} key={entry.term} />)}</div>{!entries.length && <p className="dictionary-empty">No definition matches this search yet. Try a broader word or choose All topics.</p>}</section></main>;
}
